### ISSUE TITLE
Error Compiling HarbourPP

### ISSUE THREAD

**Issue by mhsabado** [harbourplusplus/harbourpp-v1#3]
Hi Marcos,

I have the ff error with compiling with MSVC.  

************************************************************
cl.exe   -I. -I../../../../../include -nologo -TP -W4 -wd4127 -O2  -DUNICODE  -Fogdiplusflat.obj  -c ../../../gdiplusflat.cpp
gdiplusflat.cpp
../../../gdiplusflat.cpp(38): fatal error C1083: Cannot open include file: 'gdiplus/gdiplus.h': No such file or directory
win-make[3]: *** [../../../../../config/rules.mk:109: gdiplusflat.obj] Error 2
win-make[2]: *** [../../config/lib.mk:64: descend] Error 2
win-make[1]: *** [../config/dir.mk:71: winapi] Error 2
win-make: *** [config/dir.mk:71: src] Error 2
***************************************************************

Thanks,
Mario

**Comment by marcosgambeta** [comment]
Please, try again after this commit:

https://github.com/marcosgambeta/harbourpp-v1/commit/c728edf7b3e6e1a49a5e8b8088812abca0f24a7f

**Comment by mhsabado** [comment]
HI Marcos,

It compiles fine now after this commit.

Thank you very much!

Best regards,
Mario
